import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Plus, Search, Bell, LayoutDashboard, Cable, Workflow, Activity, Settings, Layers, ShieldCheck, Cloud, Server, Folder, X, Play, CheckCircle2, BookOpen } from 'lucide-react';
import './styles.css';
import { ConfigurationFields, ConnectorPanel, defaults } from './ConnectorPanel';
import TransferHistory from './TransferHistory';
import DataFlows from './DataFlows';
import Samples from './Samples';
import AS2Messages from './AS2Messages';
import ConnectorInbox from './ConnectorInbox';
import Documentation from './Documentation';
import {connectorLabel} from './connectorLabels';
import {api} from './api';

const protocols = [{name:'HTTP',label:'HTTP file inbox and partner requests',icon:Cloud,color:'green'},{name:'HTTPS',label:'HTTP transfers over TLS',icon:ShieldCheck,color:'green'},{name:'FTP',label:'FTP file transfers and NAS listener',icon:Server,color:'blue'},{name:'FTPS',label:'FTP over verified TLS',icon:ShieldCheck,color:'blue'},{name:'KAFKA',label:'Publish and consume topic records',icon:Activity,color:'purple'},{name:'LDAP',label:'Directory lookup and authentication',icon:ShieldCheck,color:'orange'},{name:'SHAREPOINT',label:'Document library transfers',icon:Cloud,color:'green'},{name:'AS2', label:'Secure B2B messaging',icon:ShieldCheck,color:'purple'}, {name:'SFTP',label:'File transfer over SSH',icon:Server,color:'blue'}, {name:'SMB',label:'NAS network file shares',icon:Folder,color:'orange'}, {name:'GCS',label:'Object storage buckets',icon:Cloud,color:'green'}, {name:'FILE',label:'Mounted NAS folder',icon:Folder,color:'orange'}, {name:'EMS',label:'JMS queue and topic publishing',icon:Server,color:'blue'}];
function App(){
 const [page,setPage]=useState('Overview'),[connections,setConnections]=useState([]),[runs,setRuns]=useState([]),[online,setOnline]=useState(false),[modal,setModal]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[notice,setNotice]=useState('');
 const [form,setForm]=useState({name:'',protocol:'SFTP',endpoint:'',config:defaults('SFTP')}),[source,setSource]=useState('JSON'),[target,setTarget]=useState('XML'),[payload,setPayload]=useState('{\n  "order_id": "PO-2026-1042",\n  "partner": "Acme Supply",\n  "amount": 2450,\n  "currency": "USD"\n}'),[mapping,setMapping]=useState('{}'),[output,setOutput]=useState('');
 async function refresh(){try { const [c,r]=await Promise.all([api('connections'),api('runs')]);setConnections(c);setRuns(r);setOnline(true); }catch{setOnline(false);}}
 useEffect(()=>{refresh();},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{await api('connections',form);setNotice('Connection test passed. Connection saved.');await refresh();setModal(false);setForm({name:'',protocol:'SFTP',endpoint:'',config:defaults('SFTP')});}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function transform(){setBusy(true);setError('');try{const m=JSON.parse(mapping);if(!m || Array.isArray(m) || typeof m!=='object')throw new Error('Mapping must be a JSON object');const r=await api('transform',{payload,source_format:source,target_format:target,mapping:m});setOutput(r.output);await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const filtered=connections.filter(c=>(c.name+c.protocol+c.endpoint).toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><aside><a className="brand" href="#" onClick={()=>setPage('Overview')}><span className="brand-icon"><Layers size={23}/></span>relay<span className="brand-dot">.</span></a><div className="workspace"><span className="avatar">N</span><div>My workspace<small>Development</small></div><span className="chevron">âŒ„</span></div><div className="nav-label">WORKSPACE</div><nav>{[[LayoutDashboard,'Overview'],[Cable,'Connections'],[Workflow,'Data Flows'],[Workflow,'Transformations'],[Activity,'Activity'],[Layers,'Samples'],[BookOpen,'Documentation']].map(([Icon,name])=><button key={name} className={page===name?'active':''} onClick={()=>{setPage(name);setError('');}}><Icon size={19}/>{name}{name==='Connections'&&<span className="count">{connections.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="help"><span className="mini-logo">âœ¦</span><strong>Built to connect.</strong><p>Your partners. Your protocols.<br/>One connected workspace.</p><button onClick={()=>setPage('Connections')}>Explore connections <ArrowUpRight size={14}/></button></div><button className="settings" onClick={()=>setPage('Settings')}><Settings size={18}/> Workspace settings</button><div className="profile"><span className="avatar dark">N</span><div>Workspace admin<small>Local development</small></div></div></div></aside><main><header><span>Workspace <span className="slash">/</span> <strong>{page}</strong></span><div><span className={'api-status '+(online?'ready':'')}>{online?'API connected':'API offline'}</span><button className="icon-button" aria-label="Show activity" onClick={()=>setPage('Activity')}><Bell size={18}/></button><span className="avatar small">N</span></div></header><div className="content"><div className="heading"><div><div className="eyebrow">YOUR B2B COMMAND CENTER</div><h1>{page==='Overview'?'Everything connected.':page}</h1><p>{page==='Overview'?'Move data between partners. Transform it into possibilities.':'Manage your integration workspace with confidence.'}</p></div><button className="primary" onClick={()=>{setError('');setModal(true);}}><Plus size={17}/>New connection</button></div>{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
 {page==='Overview'&&<><div className="stats">{[['Connection profiles',connections.length,'Partner and connector profiles',Cable],['Transformations run',runs.length,'Saved in your local workspace',Workflow],['Endpoint types',protocols.length,'AS2 Â· SFTP Â· SMB Â· GCS Â· NAS Â· EMS',Layers],['Environment','Local','Development workspace',Activity]].map(([label,value,detail,Icon])=><div className="stat" key={label}><div>{label}<Icon size={18}/></div><strong>{value}</strong><small>{detail}</small></div>)}</div><section className="start-banner"><div><span className="badge">A MORE CONNECTED WORKFLOW</span><h2>From incoming files to<br/>business-ready data.</h2><p>Connect a partner, shape your data, and bring every exchange into view.</p><button onClick={()=>setPage('Transformations')}>Build a transformation <ArrowRight size={16}/></button></div><div className="pipeline"><div className="flow-node"><Server/><span>Receive<small>Partner data</small></span></div><div className="flow-line"/><div className="flow-node special"><Workflow/><span>Transform<small>Your mapping</small></span></div><div className="flow-line"/><div className="flow-node"><CheckCircle2/><span>Deliver<small>Ready to use</small></span></div></div></section><div className="section-heading"><div><h2>Every protocol. One place.</h2><p>Choose how you connect with your trading partners.</p></div><span className="subtle">CONNECTION LIBRARY</span></div><div className="protocols">{protocols.map(({name,label,icon:Icon,color})=><button className="protocol" key={name} onClick={()=>{setForm({...form,protocol:name,config:defaults(name)});setError('');setModal(true);}}><span className={'protocol-icon '+color}><Icon size={23}/></span><ArrowUpRight className="card-arrow" size={17}/><h3>{connectorLabel(name)}</h3><p>{label}</p><span className="protocol-footer">Configure connection <ArrowRight size={14}/></span></button>)}</div></>}
 {(page==='Overview'||page==='Connections')&&<section className="table-panel"><div className="table-heading"><div><h2>Your connections <span>{connections.length}</span></h2><p>Partner endpoints, all in one view.</p></div><label className="search"><Search size={16}/><input placeholder="Search connections" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-scroll"><table><thead><tr><th>CONNECTION NAME</th><th>PROTOCOL</th><th>ENDPOINT</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><span className="row-icon"><Cable size={16}/></span><strong>{c.name}</strong><small className="connection-check" title={c.connection_test?.tested_at}>{c.connection_test?.success?'Test passed at save':'Not tested at save'}</small></td><td><span className="tag">{connectorLabel(c.protocol)}</span></td><td className="endpoint">{c.endpoint||(c.config.config_key?`${c.protocol}.${c.config.config_key}.properties`:'')}</td><td><button className="secondary" onClick={()=>setSelected(c)}>Open connection <ArrowUpRight size={13}/></button></td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="empty"><Cable size={27}/><strong>{query?'No matching connections':'Your next connection starts here'}</strong><p>{query?'Try another search.':'Add your first partner endpoint to get started.'}</p>{!query&&<button className="secondary" onClick={()=>setModal(true)}><Plus size={15}/>Add connection</button>}</div>}<div className="table-note">Open a connection to test, browse, send, or receive files. Configure credentials on the Python server.</div></section>}
 {page==='Transformations'&&<section className="editor-panel"><div className="section-heading"><div><h2>Transformation studio</h2><p>Transform flat JSON objects or XML child elements.</p></div><button className="primary" disabled={busy} onClick={transform}><Play size={16}/>{busy?'Runningâ€¦':'Run transformation'}</button></div><div className="editors"><label>Source format<select value={source} onChange={e=>setSource(e.target.value)}><option>JSON</option><option>XML</option></select><textarea aria-label="Source payload" value={payload} onChange={e=>setPayload(e.target.value)}/></label><label>Target format<select value={target} onChange={e=>setTarget(e.target.value)}><option>XML</option><option>JSON</option></select><textarea aria-label="Transformation output" readOnly value={output} placeholder="Your transformed data will appear here"/></label></div><label className="mapping-label">Field mapping <small>JSON object: target field â†’ source field. Use {'{}'} to preserve all fields.</small><textarea value={mapping} aria-label="Field mapping" onChange={e=>setMapping(e.target.value)}/></label></section>}
 {page==='Documentation'&&<Documentation/>}
 {page==='Data Flows'&&<DataFlows connections={connections}/>}
 {page==='Samples'&&<Samples onUse={sample=>{setForm({...sample,config:{...defaults(sample.protocol),...sample.config}});setError('');setModal(true);}}/>}
 {page==='Activity'&&<><AS2Messages/><ConnectorInbox/><TransferHistory/></>}
 {page==='Activity'&&<section className="table-panel"><div className="table-heading"><div><h2>Transformation history</h2><p>Your latest 50 local runs.</p></div><button className="secondary" onClick={refresh}>Refresh</button></div>{runs.length?runs.map(r=><details className="run" key={r.id}><summary><CheckCircle2 size={18}/><strong>Transformation completed</strong><span>{new Date(r.created).toLocaleString()}</span></summary><pre>{r.output}</pre></details>):<div className="empty"><Activity/><strong>No runs yet</strong><p>Run a transformation to see it here.</p></div>}</section>}
 {page==='Settings'&&<section className="table-panel settings-panel"><h2>Development workspace</h2><p>API status: {online?'Connected':'Offline'}</p><p>Profiles and run history are stored in SQLite on your Python server.</p><p>HTTP, FTP, File, event stream, LDAP, SFTP, document library and SMB connectors are available alongside AS2, GCS and JMS publishing. Use Data Flows to route files. Secrets resolve from server environment variables. AS2 supports synchronous and asynchronous signed receipts. This workspace runs locally.</p></section>}
 <footer><span><span className="footer-dot"/> Relay workspace</span><span>Made for meaningful connections.</span></footer></div></main>{modal&&<div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-title"><h2>New connection</h2><button type="button" className="icon-button" aria-label="Close" disabled={busy} onClick={()=>setModal(false)}><X size={20}/></button></div><p>Create a partner connection profile.</p>{error&&<div className="error" role="alert">{error}</div>}<fieldset className="connection-fields" disabled={busy}><label>Connection name<input required maxLength={100} placeholder="e.g. Acme orders" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Protocol<select value={form.protocol} onChange={e=>setForm({...form,protocol:e.target.value,config:defaults(e.target.value)})}>{protocols.map(p=><option key={p.name} value={p.name}>{connectorLabel(p.name)}</option>)}</select></label><label>Endpoint{form.config.config_key&&' (optional with configuration key)'}<input required={!(form.config.config_key)} maxLength={500} placeholder={form.protocol==='KAFKA'?'kafka://broker.example:9092':form.protocol==='FILE'?'D:\\NAS\\outbound':form.protocol==='EMS'?'tcp://ems.example:7222':form.protocol==='GCS'?'gs://your-bucket':form.protocol==='SMB'?'\\\\server\\share':form.protocol==='AS2'?'https://partner.example/as2':'sftp://partner.example:22'} value={form.endpoint} onChange={e=>setForm({...form,endpoint:e.target.value})}/></label><ConfigurationFields protocol={form.protocol} config={form.config||defaults(form.protocol)} onChange={config=>setForm({...form,config})}/><div className="notice">Use environment variable names for inline credentials, or a configuration key for a server properties file. Secret values stay on your Python server and are never saved in connection profiles. Saving tests these settings first; a failed test keeps the form open.</div><div className="notice">The check verifies connector access without transferring a document. AS2 also requires a test document exchange to verify receipts and interoperability.</div><button className="primary" disabled={busy}>{busy?'Testing connection...':'Test & save connection'}<ArrowRight size={16}/></button></fieldset></form></div>}{selected&&<ConnectorPanel key={selected.id} connection={selected} onClose={()=>setSelected(null)} onSaved={refresh}/>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
